variables:
  CI_DEPLOY_DIR: ${SERVER_PATH_PROJECT}

build:
  stage: build
  before_script:
  - npm install
  artefacts:
    expire_in: 1 days
    paths:
      - dist
  script:
    - npm run build
    - rm -r ./node_modules

deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - sudo cp -r ./dist $CI_DEPLOY_DIR
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'